### PR TITLE
bug fix

### PR DESCRIPTION
**Pull request by lebeier**
changed getattr to get for pipeline_settings
added "browserified" back into the output_extension

### CODE REVIEW

**Comment by lebeier** [comment]
I just realized that I accidentally removed the change while rebasing 15 days ago.

**Comment by zanderle** [comment]
Will this be merged soon? The compiler doesn't work without this fix.

**Comment by j0hnsmith** [comment]
sorry for the delay

**Comment by j0hnsmith** [comment]
@zanderle can you confirm that it works and I'll push a new version to pypi

**Comment by zanderle** [comment]
I can confirm it works, but it would probably be a good idea to add a simple `Requires django-pipeline >= 1.6` in README, since it won't work otherwise.

**Comment by j0hnsmith** [comment]
@zanderle I made `django-pipeline>=1.6.0` a dependency and pushed to pypi. Thanks for your help.

**Pull request merged**
